baseURL: "https://tricht.eu/"
languageCode: "en-gb"
title: "Michael van Tricht"
paginate: 100
publishDir: "docs"
enableRobotsTXT: true
 
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsstyle: "gruvbox"