baseURL: "https://tricht.eu/"
locale: "en-gb"
title: "Michael van Tricht"
pagination:
  pagerSize: 100
publishDir: "docs"

markup:
  highlight:
    style: catppuccin-mocha
    guessSyntax: true
  goldmark:
    renderer:
      unsafe: true