baseURL: "https://tricht.eu/"
languageCode: "en-gb"
title: "Michael van Tricht"
pagination:
  pagerSize: 100
publishDir: "docs"
enableRobotsTXT: true

markup:
  highlight:
    style: gruvbox
    guessSyntax: true
  goldmark:
    renderer:
      unsafe: true